/**
 * Mock data for the Prophet AI SOC Platform
 * This file contains all the mock data used throughout the application
 */

import type { 
  Alert, 
  Investigation, 
  Integration, 
  TeamMember, 
  Metrics, 
  Incident,
  HuntQuery,
  HuntResult,
  QueryExample,
  PerformanceMetrics,
  ChartDataPoint,
  TrendData
} from '../types';

export const mockAlerts: Alert[] = [
  {
    id: "ALT-2025-001234",
    title: "Suspicious Login from Anomalous Location",
    severity: "High",
    status: "Under Investigation",
    source: "Microsoft Entra ID",
    timestamp: "2025-06-30T20:30:15Z",
    description: "User john.smith@company.com logged in from IP 185.220.101.42 (Russia) which is outside normal geographical patterns",
    aiAnalysis: "AI has determined this is likely a compromised account based on: 1) Login from high-risk IP in Russia 2) Time of access outside normal business hours 3) No prior travel notifications 4) Different browser fingerprint",
    riskScore: 8.5,
    artifacts: ["185.220.101.42", "john.smith@company.com", "Mozilla/5.0 Firefox"],
    recommendedActions: ["Disable user account", "Force password reset", "Contact user for verification"]
  },
  {
    id: "ALT-2025-001235",
    title: "Malware Detection on Endpoint",
    severity: "Critical",
    status: "Auto-Contained",
    source: "CrowdStrike Falcon",
    timestamp: "2025-06-30T20:25:42Z",
    description: "Ransomware signature detected on LAPTOP-DEV-042 with file encryption behavior",
    aiAnalysis: "High-confidence ransomware detection. AI has automatically isolated the endpoint and blocked file encryption processes. No lateral movement detected.",
    riskScore: 9.2,
    artifacts: ["LAPTOP-DEV-042", "ransom.exe", "192.168.1.142"],
    recommendedActions: ["Keep endpoint isolated", "Run full forensic analysis", "Check for lateral movement"]
  },
  {
    id: "ALT-2025-001236",
    title: "Data Exfiltration Attempt",
    severity: "Critical",
    status: "Active Threat",
    source: "AWS GuardDuty",
    timestamp: "2025-06-30T20:20:18Z",
    description: "Unusual data transfer pattern detected from S3 bucket to external IP",
    aiAnalysis: "Potential data exfiltration detected. Large volume transfer (2.3GB) to suspicious IP address. Transfer pattern suggests automated data theft.",
    riskScore: 9.5,
    artifacts: ["s3://company-data-prod", "203.45.67.89", "2.3GB transferred"],
    recommendedActions: ["Block external IP immediately", "Review S3 access logs", "Identify compromised credentials"]
  },
  {
    id: "ALT-2025-001237",
    title: "Phishing Email Campaign",
    severity: "Medium",
    status: "Resolved",
    source: "Proofpoint Email Security",
    timestamp: "2025-06-30T19:45:33Z",
    description: "Bulk phishing emails detected targeting finance department",
    aiAnalysis: "Coordinated phishing campaign blocked. 47 emails intercepted with malicious Excel attachments. No successful deliveries detected.",
    riskScore: 6.2,
    artifacts: ["invoice_final.xlsx", "sender@fake-domain.com", "47 targets"],
    recommendedActions: ["User awareness training", "Block sender domain", "Update email filters"]
  },
  {
    id: "ALT-2025-001238",
    title: "Privilege Escalation Detected",
    severity: "High",
    status: "Investigating",
    source: "Windows Event Logs",
    timestamp: "2025-06-30T19:30:12Z",
    description: "Service account gained unexpected administrative privileges",
    aiAnalysis: "Service account SVC-BACKUP escalated to Domain Admin privileges outside maintenance window. No approved change requests found.",
    riskScore: 8.0,
    artifacts: ["SVC-BACKUP", "Domain Admins", "DC-01"],
    recommendedActions: ["Revoke elevated privileges", "Audit account activity", "Check for persistence mechanisms"]
  }
];

export const mockInvestigations: Investigation[] = [
  {
    id: "INV-2025-445",
    alertId: "ALT-2025-001234",
    status: "In Progress",
    assignedTo: "Sarah Chen",
    timeline: [
      { time: "20:30", event: "Alert generated by Entra ID" },
      { time: "20:31", event: "AI analysis completed - High risk score" },
      { time: "20:32", event: "Assigned to analyst Sarah Chen" },
      { time: "20:35", event: "IP geolocation confirmed - Russia" },
      { time: "20:37", event: "User contacted - no response" },
      { time: "20:40", event: "Account temporarily disabled" }
    ],
    evidence: [
      "Login logs showing abnormal location",
      "IP reputation data - known malicious",
      "User behavior baseline deviation",
      "No VPN usage recorded"
    ]
  },
  {
    id: "INV-2025-446",
    alertId: "ALT-2025-001235",
    status: "Completed",
    assignedTo: "Mike Rodriguez",
    timeline: [
      { time: "20:25", event: "Ransomware alert triggered by CrowdStrike" },
      { time: "20:26", event: "Endpoint automatically isolated" },
      { time: "20:27", event: "Assigned to analyst Mike Rodriguez" },
      { time: "20:30", event: "Forensic analysis initiated" },
      { time: "20:45", event: "Malware sample extracted and analyzed" },
      { time: "21:00", event: "No lateral movement detected" },
      { time: "21:15", event: "Investigation completed - contained threat" }
    ],
    evidence: [
      "Ransomware executable (ransom.exe)",
      "File encryption attempt logs",
      "Network isolation confirmation",
      "Malware analysis report",
      "System restore point created"
    ]
  },
  {
    id: "INV-2025-447",
    alertId: "ALT-2025-001236",
    status: "In Progress",
    assignedTo: "Emma Wilson",
    timeline: [
      { time: "20:20", event: "Data exfiltration alert from AWS GuardDuty" },
      { time: "20:21", event: "Large data transfer detected (2.3GB)" },
      { time: "20:22", event: "Assigned to threat hunter Emma Wilson" },
      { time: "20:25", event: "External IP blocked immediately" },
      { time: "20:30", event: "S3 access logs under review" },
      { time: "20:45", event: "Compromised API key identified" }
    ],
    evidence: [
      "S3 bucket access logs",
      "Network traffic analysis",
      "Compromised API key details",
      "Data transfer patterns",
      "External IP reputation data"
    ]
  },
  {
    id: "INV-2025-448",
    alertId: "ALT-2025-001238",
    status: "New",
    assignedTo: "David Park",
    timeline: [
      { time: "19:30", event: "Privilege escalation detected" },
      { time: "19:31", event: "Service account SVC-BACKUP gained Domain Admin" },
      { time: "19:32", event: "Assigned to SOC Manager David Park" }
    ],
    evidence: [
      "Active Directory audit logs",
      "Service account activity timeline",
      "Privilege escalation event details"
    ]
  }
];

export const mockIntegrations: Integration[] = [
  { name: "Microsoft Sentinel", status: "Connected", lastSync: "30 seconds ago", health: "Healthy" },
  { name: "CrowdStrike Falcon", status: "Connected", lastSync: "1 minute ago", health: "Healthy" },
  { name: "AWS GuardDuty", status: "Connected", lastSync: "45 seconds ago", health: "Healthy" },
  { name: "Proofpoint Email", status: "Connected", lastSync: "2 minutes ago", health: "Healthy" },
  { name: "Splunk SIEM", status: "Degraded", lastSync: "5 minutes ago", health: "Warning" },
  { name: "Okta Identity", status: "Connected", lastSync: "1 minute ago", health: "Healthy" }
];

export const mockSocTeam: TeamMember[] = [
  { name: "Sarah Chen", role: "Senior SOC Analyst", status: "Online", activeAlerts: 5 },
  { name: "Mike Rodriguez", role: "SOC Analyst", status: "Online", activeAlerts: 3 },
  { name: "Emma Wilson", role: "Threat Hunter", status: "Away", activeAlerts: 0 },
  { name: "David Park", role: "SOC Manager", status: "Online", activeAlerts: 1 }
];

export const mockMetrics: Metrics = {
  totalAlerts: 1247,
  alertsTrend: "+12%",
  activeInvestigations: 23,
  investigationsTrend: "-5%",
  resolvedIncidents: 89,
  incidentsTrend: "+8%",
  mttr: "12 min",
  mttrTrend: "-45%",
  accuracy: "94.2%",
  accuracyTrend: "+3%",
  falsePositives: "5.8%",
  falsePositivesTrend: "-15%"
};

export const mockIncidents: Incident[] = [
  {
    id: "INC-2025-001",
    title: "Data Breach Investigation",
    severity: "Critical",
    status: "In Progress",
    description: "Potential data exfiltration from customer database",
    assignedTo: "Sarah Chen",
    createdAt: "2025-06-30T18:00:00Z",
    updatedAt: "2025-06-30T20:30:00Z"
  },
  {
    id: "INC-2025-002",
    title: "Ransomware Containment",
    severity: "High",
    status: "Resolved",
    description: "Ransomware attack on development environment",
    assignedTo: "Mike Rodriguez",
    createdAt: "2025-06-30T16:00:00Z",
    updatedAt: "2025-06-30T19:00:00Z"
  },
  {
    id: "INC-2025-003",
    title: "Phishing Campaign Response",
    severity: "Medium",
    status: "New",
    description: "Large-scale phishing campaign targeting employees",
    assignedTo: "Emma Wilson",
    createdAt: "2025-06-30T21:00:00Z",
    updatedAt: "2025-06-30T21:00:00Z"
  }
];

export const mockHuntQueries: HuntQuery[] = [
  {
    id: "HQ-001",
    query: "Find all login attempts from suspicious IP addresses in the last 24 hours",
    description: "Identify potential credential stuffing attacks",
    createdAt: "2025-06-30T10:00:00Z",
    createdBy: "Emma Wilson"
  },
  {
    id: "HQ-002", 
    query: "Detect lateral movement patterns in network traffic",
    description: "Look for signs of advanced persistent threats",
    createdAt: "2025-06-30T14:30:00Z",
    createdBy: "Sarah Chen"
  }
];

export const mockHuntResults: HuntResult[] = [
  {
    id: "HR-001",
    title: "Suspicious Login Pattern",
    description: "Multiple failed attempts from IP 192.168.1.100",
    confidence: 85,
    severity: "High",
    timestamp: "2025-06-30T20:45:00Z",
    artifacts: ["192.168.1.100", "user.account@company.com", "Failed login attempts: 47"]
  },
  {
    id: "HR-002",
    title: "Lateral Movement Detected", 
    description: "Service account accessing multiple systems",
    confidence: 92,
    severity: "Critical",
    timestamp: "2025-06-30T20:42:00Z",
    artifacts: ["SVC-BACKUP", "Multiple system access", "Privilege escalation"]
  },
  {
    id: "HR-003",
    title: "Data Transfer Anomaly",
    description: "Large file transfer during off-hours",
    confidence: 78,
    severity: "Medium", 
    timestamp: "2025-06-30T20:38:00Z",
    artifacts: ["2.3GB transfer", "External IP: 203.45.67.89", "Off-hours activity"]
  }
];

export const mockQueryExamples: QueryExample[] = [
  {
    title: "Failed Login Analysis",
    query: "Find all failed login attempts in the last hour",
    description: "Identify potential brute force attacks",
    category: "Authentication"
  },
  {
    title: "Suspicious File Activity",
    query: "Detect unusual file access patterns",
    description: "Look for potential data exfiltration",
    category: "Data Protection"
  },
  {
    title: "Network Anomalies",
    query: "Find abnormal network traffic patterns",
    description: "Identify potential command and control communications",
    category: "Network Security"
  },
  {
    title: "Privilege Escalation",
    query: "Detect unauthorized privilege changes",
    description: "Find accounts gaining unexpected permissions",
    category: "Access Control"
  }
];

export const mockPerformanceMetrics: PerformanceMetrics = {
  accuracy: 94.2,
  falsePositiveRate: 5.8,
  coverage: 87.5,
  responseTime: 12.3,
  detectionRate: 96.1
};

export const mockChartData = {
  threatLandscape: [
    { label: 'Critical', value: 2, color: '#ff4444' },
    { label: 'High', value: 8, color: '#ff8800' },
    { label: 'Medium', value: 15, color: '#ffcc00' },
    { label: 'Low', value: 25, color: '#44aaff' }
  ] as ChartDataPoint[],
  
  alertTrends: [
    { label: 'Mon', value: 45 },
    { label: 'Tue', value: 52 },
    { label: 'Wed', value: 38 },
    { label: 'Thu', value: 67 },
    { label: 'Fri', value: 89 },
    { label: 'Sat', value: 34 },
    { label: 'Sun', value: 28 }
  ] as ChartDataPoint[],
  
  responseTimes: [
    { label: '< 5 min', value: 65, color: '#00cc66' },
    { label: '5-15 min', value: 23, color: '#00d4ff' },
    { label: '15-30 min', value: 8, color: '#ffcc00' },
    { label: '30+ min', value: 4, color: '#ff4444' }
  ] as ChartDataPoint[],
  
  threatCategories: [
    { label: 'Malware', value: 25, color: '#ff4444' },
    { label: 'Phishing', value: 20, color: '#ff8800' },
    { label: 'Suspicious Login', value: 30, color: '#ffcc00' },
    { label: 'Data Exfiltration', value: 15, color: '#44aaff' },
    { label: 'Privilege Escalation', value: 10, color: '#00cc66' }
  ] as ChartDataPoint[]
};

export const mockTrendData: TrendData[] = [
  { period: 'Last 7 days', value: 1247, change: 12, changePercent: '+12%' },
  { period: 'Last 30 days', value: 4892, change: -5, changePercent: '-5%' },
  { period: 'Last 90 days', value: 14567, change: 8, changePercent: '+8%' }
];

// Utility functions for data management
export const generateAlertId = (): string => {
  const timestamp = Date.now();
  const random = Math.floor(Math.random() * 1000);
  return `ALT-2025-${timestamp.toString().slice(-6)}${random.toString().padStart(3, '0')}`;
};

export const generateInvestigationId = (): string => {
  const random = Math.floor(Math.random() * 999) + 1;
  return `INV-2025-${random.toString().padStart(3, '0')}`;
};

export const generateIncidentId = (): string => {
  const random = Math.floor(Math.random() * 999) + 1;
  return `INC-2025-${random.toString().padStart(3, '0')}`;
};

export const generateHuntQueryId = (): string => {
  const random = Math.floor(Math.random() * 999) + 1;
  return `HQ-${random.toString().padStart(3, '0')}`;
};

export const generateHuntResultId = (): string => {
  const random = Math.floor(Math.random() * 999) + 1;
  return `HR-${random.toString().padStart(3, '0')}`;
};